services:
  database:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rides
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    container_name: backend_container
    environment:
      DB_NAME: rides
      DB_USER: admin
      DB_PASSWORD: secret
      DB_HOST: database
      DB_PORT: 5432
    ports:
      - "8080:8080"
    depends_on:
      - database

volumes:
  db_data:
